server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/meetingdb?serverTimezone=GMT&characterEncoding=utf-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  jackson:
    date-format: yyyy/MM/dd HH:mm:ss
    time-zone: UTC      










